# Generated by Django 5.0.6 on 2025-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_content_media_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='banner',
            field=models.FileField(max_length=500, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='media',
            field=models.FileField(max_length=500, null=True, upload_to='contents/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='media_preview',
            field=models.FileField(max_length=500, null=True, upload_to='contents/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.FileField(max_length=500, null=True, upload_to='contents/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('content', 'Content'), ('message', 'Message')], max_length=100),
        ),
    ]
