# Generated by Django 5.0.6 on 2025-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsetting',
            name='d',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
